#-----------------------------------------------
# config.system.yaml user setting
#
# config.system.default.yamlの値をこのファイルで
# 上書きすることが出来ます。
#-----------------------------------------------

### 例 jQueryのバージョンを切り替える
# jquery_version: 3.4.1 # (3.4.1|2.1.1|2.0.3|1.11.1|1.10.1|1.9.1|1.8.3|1.7.2) 2.xはIE9〜
# jquery_migrate: migrate-3.0.1
# webp_support: on # on | off webp画像を生成するかどうかを設定

forbid_direct_access_tpl: /^_/ # off | /^_/  パスのディレクトリまたはファイルがこの正規表現に一致したものは直接表示させない
forbid_tpl_inheritance_when_path_unresolved: on # on | off パス解決に失敗した時、テンプレートを継承しないようにする
forbid_tpl_url_context: on # on | off 読者以下のURLコンテキストのtplを許可しない。（例: https://example.com/news/tpl/custom.html）
allow_tpl_path: [include/summary.html] # forbid_tpl_inheritance_when_path_unresolved や forbid_tpl_url_context が on の場合、除外するパスを設定します。例: [news.html,hoge/custom.html] カンマ区切りで指定

image_magick: off
